# Generated by Django 5.2.4 on 2025-08-02 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='can_delete',
            field=models.ManyToManyField(blank=True, related_name='documents_can_delete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='can_edit',
            field=models.ManyToManyField(blank=True, related_name='documents_can_edit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='can_view',
            field=models.ManyToManyField(blank=True, related_name='documents_can_view', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
