# Generated by Django 5.2.4 on 2025-08-07 18:27

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_can_delete_document_can_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sort_position',
            field=models.IntegerField(default=documents.models.get_random_sort_position),
        ),
    ]
